---
apiVersion: v1
kind: Namespace
metadata:
  name: soup
  labels:
    name: soup
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soup
  namespace: soup
  labels:
    app: soup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soup
  template:
    metadata:
      labels:
        app: soup
    spec:
      containers:
      - name: soup
        image: pablogcaldito/soup:0.1.0-rc3
        command: ["/bin/soup"]
        args:
          - "-repo=https://github.com/caldito/soup-test.git"
...
