---
apiVersion: v1
kind: Namespace
metadata:
  name: soup
  labels:
    name: soup
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: soup-admin
rules:
- apiGroups:
  - ""
  resources:
  - services
  - namespaces
  - pods
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: soup-admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: soup-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: soup
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soup
  namespace: soup
  labels:
    app: soup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soup
  template:
    metadata:
      labels:
        app: soup
    spec:
      containers:
      - name: soup
        image: pablogcaldito/soup:v0.3.0-rc2
        command: ["/bin/soup"]
        args:
          - "-repo=https://github.com/caldito/soup-test.git"
...
