---

name: Push container
on:
  release:
    types:
      - created
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Get tag, build and push
      run: |
        TAG=$(echo ${{ github.ref }} | sed 's/refs\/tags\///g')
        make build-docker
        echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u pablogcaldito --password-stdin
        docker push pablogcaldito/soup:"${TAG}"
        curl https://sum.golang.org/lookup/github.com/caldito/soup@${TAG}
